Party\Bundle\PrivateBundle\Entity\Party:
    type: entity
    table: pty_party
    repositoryClass: Party\Bundle\PrivateBundle\Repository\PartyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        location:
            type: string
            length: 255
        date:
            type: date
    manyToMany:
        attendees:
            targetEntity: Attendee
            cascade: ["persist"]
            joinTable:
                name: pty_party_attendee
                joinColumns:
                    party_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    attendee_id:
                        referencedColumnName: id
                        onDelete: RESTRICT
    lifecycleCallbacks: {  }
