Party\Bundle\PrivateBundle\Entity\User:
    type: entity
    table: pty_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
