Party\Bundle\PrivateBundle\Entity\User:
    type: entity
    table: pty_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
        parties:
            targetEntity: Party
            mappedBy: attendees
    lifecycleCallbacks: {  }
