public_index:
    path:     /
    defaults: { _controller: PartyPublicBundle:Home:index }

attendee_new:
    pattern: /{partyId}/rsvp
    defaults: { _controller: PartyPublicBundle:Home:new }

attendee_create:
    path:     /{partyId}/create
    defaults: { _controller: PartyPublicBundle:Home:create, partyId: null }
    requirements: { _method: post }
