parameters:
#    party_public.example.class: Party\Bundle\PublicBundle\Example

services:
#    party_public.example:
#        class: %party_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
