parameters:
#    party_private.example.class: Party\Bundle\PrivateBundle\Example

services:
#    party_private.example:
#        class: %party_private.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
